

stages:
  - build
  - deploy

variables:
  WEBAPP_NAME: "budgetbites"  # Replace with your Azure App Service name
  RESOURCE_GROUP: "app-01-bb-ue-p_group"  # Replace with your Azure resource group name
  WEBAPP_SLOT_NAME: "production"  # Replace with your deployment slot name
  CREDENTIALS: $AZURE_SERVICE_PRINCIPAL  # Azure Service Principal credential stored in GitLab CI/CD variable
  TF_JOB_NAME: 'bb'

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  tags:
    - docker
  environment:
      name: dev
  before_script:
    - apt update -y && apt -y install zip
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash    
    - az login --service-principal -u $CLIENT_ID -p $SECRET_KEY --tenant $TENANT_ID
    - az account set --subscription $CLARIUM_APP_DEV_APPLICATION_SUBSCRIPTION
  script:
    - cd BudgetBitesAPI/
    - dotnet restore
    - dotnet build
    - dotnet publish -c Release -o ./budgetbitesapi
    - cd ./budgetbitesapi
    - zip -r ./budgetbitesapi.zip *
  after_script:
    - az webapp deploy --clean true --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --src-path ./BudgetBitesAPI/budgetbitesapi/budgetbitesapi.zip --target-path /home/site/budgetbitesapi/
  artifacts:
    paths:
      - BudgetBitesAPI/budgetbitesapi/budgetbitesapi.zip
  only:
    refs:
      - dev
    variables:
      - $TF_JOB_NAME == "bb"

# deploy:
#   stage: deploy
#   tags:
#     - shell
#   environment:
#       name: dev
#   dependencies:
#     - build  
#   before_script:
#     - az login --service-principal -u $CLIENT_ID -p $SECRET_KEY --tenant $TENANT_ID
#     - az account set --subscription $CLARIUM_APP_DEV_APPLICATION_SUBSCRIPTION

#   script:
#     - mkdir bb
#     - cp -r $CI_PROJECT_DIR/BudgetBitesAPI/budgetbitesapi.zip bb/
#     - cd $CI_PROJECT_DIR/
#     - ls
#     - cd BudgetBitesAPI/
#     - ls
#     - az webapp deploy --clean true --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --src-path ./BudgetBitesAPI/budgetbitesapi.zip --target-path /home/site/wwwroot/api
#   after_script:
#     - az logout
#   only:
#     refs:
#       - dev
#     variables:
#       - $TF_JOB_NAME == "bb"