CREATE TABLE [dbo].[Dietary](
	[DietaryID] [int] IDENTITY(1,1) NOT NULL,
	[PersonID] [int] NOT NULL,
	[DietaryRestriction] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Dietary] PRIMARY KEY CLUSTERED 
(
	[DietaryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Dietary]  WITH CHECK ADD  CONSTRAINT [FK_Dietary_Persons] FOREIGN KEY([PersonID])
REFERENCES [dbo].[Persons] ([PersonID])
GO

ALTER TABLE [dbo].[Dietary] CHECK CONSTRAINT [FK_Dietary_Persons]
GO


